default_language_version:
  python: python3

# NOTE: Update in .flake8 pyproject.toml as well
exclude: |
    (?x)^(
      \.git|
      __pycache__|
      .*snap_test_.*\.py|
      .+\/.+\/migrations\/.*|
      \.venv
    )
    
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.8
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
